---
- name: Download config
  hosts: pi
  remote_user: pi
  vars:
    desktop_dir: /home/pi/Desktop
    app_dir: /home/pi/Desktop/app
    app_file: app.tar

  tasks:
  - name: Get UUID
    uri:
      url: "http://{{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}}/info"
      return_content: yes
      method: GET
      body_format: json
      status_code: 200
    register: result
    retries: 3
    delay: 10

  - debug: 
      var: result.json.id
    
  - name: Download
    copy:
      src: "{{app_dir}}/app.ini"
      dest: "/home/pi/app.ini"
      remote_src: yes

