---
- name: Update firmware
  hosts: pi_0
  remote_user: pi
  vars:
    desktop_dir: /home/pi/Desktop
    app_file: app.tar

  tasks:
  - name: Copy new version firmware to {{desktop_dir}}
    copy:
      src: "{{app_file}}"
      dest: "{{desktop_dir}}/{{app_file}}"
      backup: yes
      mode: '0777'
    register: file_app

  - name: DEBUG
    debug:
      var: file_app

  - name: Extract {{app_file}} => {{desktop_dir}}
    unarchive:
      src: "{{app_file}}"
      dest: "{{desktop_dir}}"

